### PR TITLE
[React Native 0.48]: Error: Redefinition of RCTMethodInfo

### PR DESCRIPTION
**Pull request by exentrich**
Build failed without this fix

### CODE REVIEW

**Comment by joncursi** [comment]
Confirmed working on my end. I am using @exentrich 's patch for now to get around this:

```
    "react-native-oauth": "git+ssh://git@github.com/exentrich/react-native-oauth#patch-1",
```

**Comment by Kottidev** [comment]
can you accept this PR ?

**Comment by karlAlnebratt** [comment]
Experiencing same issue.
```
"react": "16.0.0-beta.5",
"react-native": "0.49.1",
"react-native-oauth": "2.2.0"
```
I'm using [patch-package](https://www.npmjs.com/package/patch-package) to fix this issue until this is released.

**Comment by tqc** [comment]
The code modified in this PR isn't actually the problem. The error comes up because there are multiple versions of the react native headers in the search path - the older version exists, but isn't the one you are actually using. 

Assuming you have a fairly standard setup, deleting node_modules/react-native and reinstalling should work - a lot of files got moved to different locations around 0.48, so the old ones may not get overwritten/removed with an upgrade.

**Comment by mackenziemance** [comment]
Is @tqc 's  solution working for anyone els ? I'm only able to solve this with the patch

**Comment by developersoul** [comment]
works for me!  thanks @exentrich

**Comment by dsznajder** [comment]
Working with 0.51.0 too. This should be merged a few days ago when I started debugging this one 💃

**Comment by melihmucuk** [comment]
Im running on react-native v0.51.0 and it doesnt work with current npm version. Please merge this pull request to fix it.

**Comment by mraible** [comment]
I ran into this today, using the latest and greatest react-native code (`^0.52.2`). I can confirm that using the following solved the problem:

```
"react-native-oauth": "git+ssh://git@github.com/exentrich/react-native-oauth#patch-1",
```

**Comment by Compulsor** [comment]
Can this PLEASE get merged. For crying out loud.

**Comment by cranberyxl** [comment]
We forked it and are using the patch mentioned above.

**Comment by sb8244** [comment]
This is still occurring and the only solution right now is to the use the forked patch. Is this going to be merged? Is there a better solution?
